# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Catraca

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Compilador Teste
      run: |
           cd src
           javac -cp . Teste.java
    - name: Rodando o Programa em Teste
      run: |
          cd src
          java -cp . Teste
    - name: Compilador Main
      run: |
           cd src
           javac -cp . Main.java
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Deploy Docker image
      with:
           
           image: fidasgabriel/aula_deploy_dockerhub
           tags: ${{ github.run_number }}
           registry: docker.io
           dockerfile: dockerfile
           username: ${{ secrets.DOCKER_USER }}
           password: ${{ secrets.DOCKER_PASSWORD }}


